# Generated by Django 4.2 on 2025-11-23 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('genres', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['-avg_rating', '-rating_count'],
            },
        ),
        migrations.CreateModel(
            name='RawDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('record_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'raw_dataset',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_categories', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preference',
            },
        ),
        migrations.CreateModel(
            name='RecommendationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_score', models.FloatField(default=0.0)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('genre_match_score', models.FloatField(blank=True, default=0.0, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='app.movie')),
            ],
            options={
                'db_table': 'recommendation_data',
                'ordering': ['-recommendation_score'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('rating', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app.movie')),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.AddIndex(
            model_name='recommendationdata',
            index=models.Index(fields=['user_id', '-recommendation_score'], name='recommendat_user_id_989b13_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user_id', 'rating'], name='ratings_user_id_b7af4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user_id', 'movie')},
        ),
    ]
